## Pre-Assignment

**1. Documentation reading - A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness). See the documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).**

I reviewed the `torch.Tensor` documentation.

**2. Create a random tensor with shape `(7, 7)`.**

In [28]:
import torch

In [29]:
random_tensor_1=torch.rand(7,7)
random_tensor_1

tensor([[0.2685, 0.7970, 0.2670, 0.5233, 0.0389, 0.1146, 0.5563],
        [0.7264, 0.3471, 0.8083, 0.0683, 0.1322, 0.1599, 0.4492],
        [0.3483, 0.8405, 0.2395, 0.9431, 0.0910, 0.3146, 0.2048],
        [0.7750, 0.5175, 0.5690, 0.9269, 0.8084, 0.9405, 0.3079],
        [0.2288, 0.7924, 0.3338, 0.5012, 0.6888, 0.6682, 0.1368],
        [0.3598, 0.8933, 0.3685, 0.8899, 0.3061, 0.7736, 0.3808],
        [0.3363, 0.2611, 0.6155, 0.7038, 0.8805, 0.2959, 0.3854]])

I created random tensor with shape (7, 7).

**3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).**

In [30]:
random_tensor_2=torch.rand(1,7)
random_tensor_2

tensor([[0.6922, 0.8189, 0.7983, 0.5487, 0.2411, 0.3273, 0.1010]])

I created random tensor with shape (1, 7).

In [31]:
result=torch.mm(random_tensor_1,random_tensor_2.T)
result

tensor([[1.4419],
        [1.5994],
        [1.7837],
        [2.4569],
        [1.7473],
        [2.1285],
        [1.6723]])

I transposed the 2nd tensor to (7,1) and performed multiplication.

**4. Make a tensor vector `a` of all ones with length `5` and then change this torch tensor to a numpy array `b` and print out `b`. Modify the third entry of `a` to `0` and print out `b`. Modify the fourth entry of `b` to `5` and print out `a`. What do you observe in terms of values of `a` and `b`?**

In [32]:
import numpy as np

In [33]:
a = torch.ones(5)
a

tensor([1., 1., 1., 1., 1.])

In [34]:
b = a.numpy()
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [35]:
a[2] = 0
b

array([1., 1., 0., 1., 1.], dtype=float32)

In [36]:
b[3] = 5
a

tensor([1., 1., 0., 5., 1.])

I followed the instruction and observe `a` and `b` are changed simultaneously, because they share a same memory.