# Quick refresher on Python

Python is a high-level, dynamically typed multiparadigm programming language. Python code is often said to be almost like pseudocode, since it allows you to express very powerful ideas in very few lines of code while being very readable.

This notebook is adapted from the notebook in [CS224N: Natural Language Processing with Deep Learning](https://web.stanford.edu/class/cs224n/) at Stanford.

In this notebook, we give a quick review on Python. We will
cover

* Basic Python: Basic data types (Containers, Lists, Dictionaries, Sets, Tuples), Functions, Classes, Loops
* Numpy: Arrays, Array indexing, Datatypes, Array math, Broadcasting

You can check your Python version at the command line by running python --version.

In [1]:
!python --version

Python 3.12.12


## Basic data types and operations

### Numbers

Integers and floats work as you would expect from other languages:

In [2]:
x = 3
print(x, type(x))

3 <class 'int'>


In [3]:
print(x + 1)   # Addition
print(x - 1)   # Subtraction
print(x * 2)   # Multiplication
print(x ** 2)  # Exponentiation

4
2
6
9


In [4]:
x += 1
print(x)
x *= 2
print(x)

4
8


In [5]:
y = 2.5
print(type(y))
print(y, y + 1, y * 2, y ** 2)

<class 'float'>
2.5 3.5 5.0 6.25


### Booleans

Python implements all of the usual operators for Boolean logic, but uses English words rather than symbols (&&, ||, etc.):

In [6]:
t, f = True, False
print(type(t))

<class 'bool'>


In [7]:
print(t and f) # Logical AND;
print(t or f)  # Logical OR;
print(not t)   # Logical NOT;
print(t != f)  # Logical XOR;

False
True
False
True


### Strings

You can find a list of all string methods in the [documentation](https://docs.python.org/3.7/library/stdtypes.html#string-methods).

In [8]:
hello = 'hello'   # String literals can use single quotes
world = "world"   # or double quotes; it does not matter
print(hello, len(hello))

hello 5


In [9]:
hw = hello + ' ' + world  # String concatenation
print(hw)

hello world


In [10]:
hw12 = '{} {} {}'.format(hello, world, 12)  # string formatting
print(hw12)

hello world 12


In [11]:
s = "hello"
print(s.capitalize())  # Capitalize a string
print(s.upper())       # Convert a string to uppercase; prints "HELLO"
print(s.rjust(7))      # Right-justify a string, padding with spaces
print(s.center(7))     # Center a string, padding with spaces
print(s.replace('l', '(ell)'))  # Replace all instances of one substring with another
print('  world '.strip())  # Strip leading and trailing whitespace

Hello
HELLO
  hello
 hello 
he(ell)(ell)o
world


## Collections

Python has several built-in types that are useful for storing and manipulating data: list, tuple, dict. Here is the official Python documentation on these types (and many others): https://docs.python.org/3/library/stdtypes.html.

### Lists

Lists are mutable arrays (you can change the object's state after you've created it). Let's see how they work.

In [12]:
names = ["Zach", "Jay"]

In [13]:
# Index into list by index
print(names[0])

Zach


In [14]:
# Append to list (appends to end of list)
names.append("Richard")
print(names)

['Zach', 'Jay', 'Richard']


In [15]:
# Get length of list
print(len(names))

3


In [16]:
# Concatenate two lists
# += operator is a short hand for list1 = list1 + list2 (can also be used for -, *, / and on other types of variables)
names += ["Abi", "Kevin"]
print(names)

['Zach', 'Jay', 'Richard', 'Abi', 'Kevin']


In [17]:
# Two ways to create an empty list
more_names = []
more_names = list()

In [18]:
# Create a list that contains different data types, this is allowed in Python
stuff = [1, ["hi", "bye"], -0.12, None]
print(stuff)

[1, ['hi', 'bye'], -0.12, None]


List slicing is a useful way to access a slice of elements in a list.

In [19]:
numbers = [0, 1, 2, 3, 4, 5, 6]

# Slices from start index (inclusive) to end index (exclusive)
print(numbers[0:3])

[0, 1, 2]


In [20]:
# When start index is not specified, it is start of list
# When end index is not specified, it is end of list
print(numbers[:3])
print(numbers[5:])

[0, 1, 2]
[5, 6]


In [21]:
# : takes the slice of all elements along a dimension, is very useful when working with numpy arrays
print(numbers[:])

[0, 1, 2, 3, 4, 5, 6]


In [22]:
# Negative index wraps around, start counting from the end of list
print(numbers[-1])
print(numbers[-3:])
print(numbers[3:-2])

6
[4, 5, 6]
[3, 4]


### Tuples

Tuples are immutable arrays (cannot be changed after creation). Let's see how they work.

In [23]:
# Use parentheses for tuples, square brackets for lists
names = ("Zach", "Jay")

In [24]:
# Syntax for accessing an element and getting length are the same as lists
print(names[0])
print(len(names))

Zach
2


In [25]:
# But unlike lists, tuples do not support item re-assignment
names[0] = "Richard"

TypeError: 'tuple' object does not support item assignment

In [26]:
# Create an empty tuple
empty = tuple()
print(empty)

# Create a tuple with a single item, the comma is important
single = (10,)
print(single)

()
(10,)


### Dictionary

Dictionaries are hash maps. Let's see how they work.

In [27]:
# Two ways to create an empty dictionary
phonebook = {}
phonebook = dict()

In [28]:
# Create dictionary with one item
phonebook = {"Zach": "12-37"}
# Add another item
phonebook["Jay"] = "34-23"

In [29]:
# Check if a key is in the dictionary
print("Zach" in phonebook)
print("Kevin" in phonebook)

True
False


In [30]:
# Get corresponding value for a key
print(phonebook["Jay"])

34-23


In [31]:
print(phonebook.get('Kevin', 'N/A'))    # Get an element with a default; prints "N/A"
print(phonebook.get('Jay', 'N/A'))    # Get an element with a default; prints "34-23"

N/A
34-23


In [32]:
# Delete an item
del phonebook["Zach"]
print(phonebook)

{'Jay': '34-23'}


### Sets



A set is an unordered collection of distinct elements. As a simple example, consider the following:

In [33]:
animals = {'cat', 'dog'}
print('cat' in animals)   # Check if an element is in a set; prints "True"
print('fish' in animals)  # prints "False"

True
False


In [34]:
animals.add('fish')      # Add an element to a set
print('fish' in animals)
print(len(animals))       # Number of elements in a set;

True
3


## Loops

In [35]:
# Basic for loop
for i in range(5):
    print(i)

0
1
2
3
4


In [36]:
# To iterate over a list
names = ["Zach", "Jay", "Richard"]
for name in names:
    print(name)

Zach
Jay
Richard


In [37]:
# To iterate over indices and values in a list
# Way 1
for i in range(len(names)):
    print(i, names[i])

print("---")

# Way 2
for i, name in enumerate(names):
    print(i, name)

0 Zach
1 Jay
2 Richard
---
0 Zach
1 Jay
2 Richard


In [38]:
# To iterate over a dictionary
phonebook = {"Zach": "12-37", "Jay": "34-23"}

# Iterate over keys
for name in phonebook:
    print(name)

print("---")

# Iterate over values
for number in phonebook.values():
    print(number)

print("---")

# Iterate over keys and values
for name, number in phonebook.items():
    print(name, number)

Zach
Jay
---
12-37
34-23
---
Zach 12-37
Jay 34-23


## Functions

Python functions are defined using the `def` keyword. For example:

In [39]:
def sign(x):
    if x > 0:
        return 'positive'
    elif x < 0:
        return 'negative'
    else:
        return 'zero'

for x in [-1, 0, 1]:
    print(sign(x))

negative
zero
positive


We will often define functions to take optional keyword arguments, like this:

In [40]:
def hello(name, loud=False):
    if loud:
        print('HELLO, {}'.format(name.upper()))
    else:
        print('Hello, {}!'.format(name))

hello('Bob')
hello('Fred', loud=True)

Hello, Bob!
HELLO, FRED


## Classes

The syntax for defining classes in Python is straightforward:

In [41]:
class Greeter:

    # Constructor
    def __init__(self, name):
        self.name = name  # Create an instance variable

    # Instance method
    def greet(self, loud=False):
        if loud:
          print('HELLO, {}'.format(self.name.upper()))
        else:
          print('Hello, {}!'.format(self.name))

g = Greeter('Fred')  # Construct an instance of the Greeter class
g.greet()            # Call an instance method; prints "Hello, Fred"
g.greet(loud=True)   # Call an instance method; prints "HELLO, FRED!"

Hello, Fred!
HELLO, FRED


## NumPy
NumPy is a Python library, which adds support for large, multi-dimensional arrays and matrices, along with a large collection of optimized, high-level mathematical functions to operate on these arrays.

You may need to install numpy first before importing it in the next cell.

In [42]:
# Import numpy
import numpy as np

In [43]:
# Create numpy arrays from lists
x = np.array([1,2,3])
a = np.array([[1,2,3]])


y = np.array([[3,4,5]])
z = np.array([[6,7],[8,9]])

# Let's take a look at their shapes.
# When working with numpy arrays, .shape will be a very useful debugging tool
print(x.shape)
print(y.shape)
print()
print(z)
print(z.shape)

(3,)
(1, 3)

[[6 7]
 [8 9]]
(2, 2)


Vectors can be represented as 1-D arrays of shape (N,) or 2-D arrays of shape (N, 1) or (1, N). But it's important to note that the shapes (N,), (N, 1), and (1,N) are not the same and may result in different behavior (we'll see some examples below involving matrix multiplication and broadcasting).

Matrices are generally represented as 2-D arrays of shape (M, N).

The best way to ensure your code gives you the behavior you expect is to keep track of your array shapes and try out small test cases or refer back to documentation when you are unsure.

In [44]:
a = np.arange(10)
b = a.reshape((5, 2))
print(a)
print()
print(b)

[0 1 2 3 4 5 6 7 8 9]

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


### Array Operations

There are many NumPy operations that can be used to reduce a numpy array along an axis.

Let's look at the np.max operation (documentation: https://numpy.org/doc/stable/reference/generated/numpy.ndarray.max.html).

In [45]:
x = np.array([[1,2],[3,4], [5, 6]])
print(x)
print()
print(x.shape)

[[1 2]
 [3 4]
 [5 6]]

(3, 2)


In [46]:
print(np.max(x, axis = 1))

[2 4 6]


In [47]:
print(np.max(x, axis = 1).shape)

(3,)


In [48]:
print(np.max(x, axis = 1, keepdims = True))

[[2]
 [4]
 [6]]


In [49]:
print(np.max(x, axis = 1, keepdims = True).shape)

(3, 1)


Next, let's look at some matrix operations. Let's take an element-wise product (Hadamard product).

In [50]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[3, 3], [3, 3]])
print(A)
print(B)
print("---")
print(A * B)

[[1 2]
 [3 4]]
[[3 3]
 [3 3]]
---
[[ 3  6]
 [ 9 12]]


We can do matrix multiplication with np.matmul or @.

In [51]:
# One way to do matrix multiplication
print(np.matmul(A, B))

# Another way to do matrix multiplication
print(A @ B)

[[ 9  9]
 [21 21]]
[[ 9  9]
 [21 21]]


We can take the dot product or a matrix vector product with np.dot.

In [52]:
u = np.array([1, 2, 3])
v = np.array([1, 10, 100])

print(np.dot(u, v))

# Can also call numpy operations on the numpy array, useful for chaining together multiple operations
print(u.dot(v))

321
321


In [53]:
W = np.array([[1, 2], [3, 4], [5, 6]])
print(v.shape)
print(W.shape)

# This works.
print(np.dot(v, W))
print(np.dot(v, W).shape)

(3,)
(3, 2)
[531 642]
(2,)


In [54]:
# This does not. Why?
print(np.dot(W, v))

ValueError: shapes (3,2) and (3,) not aligned: 2 (dim 1) != 3 (dim 0)

In [55]:
# We can fix the above issue by transposing W.
print(np.dot(W.T, v))
print(np.dot(W.T, v).shape)

[531 642]
(2,)


###  Indexing

Slicing / indexing numpy arrays is a extension of the Python concept of slicing (lists) to N dimensions.

In [56]:
x = np.random.random((3, 4))

# Selects all of x
print(x[:])

[[0.39791441 0.68184945 0.75163885 0.07945581]
 [0.3476284  0.96732256 0.68476133 0.02156566]
 [0.1723229  0.53759105 0.60280066 0.26664099]]


In [57]:
# Selects the 0th and 2nd rows
print(x[np.array([0, 2]), :])

print("---")

# Selects 1st row as 1-D vector and and 1st through 2nd elements
print(x[1, 1:3])

[[0.39791441 0.68184945 0.75163885 0.07945581]
 [0.1723229  0.53759105 0.60280066 0.26664099]]
---
[0.96732256 0.68476133]


In [58]:
# Boolean indexing
print(x[x > 0.5])

[0.68184945 0.75163885 0.96732256 0.68476133 0.53759105 0.60280066]


In [59]:
# 3-D vector of shape (3, 4, 1)
print(x[:, :, np.newaxis])

[[[0.39791441]
  [0.68184945]
  [0.75163885]
  [0.07945581]]

 [[0.3476284 ]
  [0.96732256]
  [0.68476133]
  [0.02156566]]

 [[0.1723229 ]
  [0.53759105]
  [0.60280066]
  [0.26664099]]]


### Broadcasting

The term broadcasting describes how NumPy treats arrays with different shapes during arithmetic operations.

**General Broadcasting Rules**

When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing (i.e. rightmost) dimensions and works its way left. Two dimensions are compatible when:
- they are equal, or
- one of them is 1 (in which case, elements on the axis are repeated along the dimension)

See more details and examples: https://numpy.org/doc/stable/user/basics.broadcasting.html

**Note**: If you're getting an error, print the shapes of the matrices and investigate from there.

In [60]:
x = np.random.random((3, 4))

y = np.random.random((3, 1))
z = np.random.random((1, 4))

# In this example, y and z are broadcasted to match the shape of x.
# y is broadcasted along dim 1.
s = x + y
# z is broadcasted along dim 0.
p = x * z

In [61]:
print(x.shape)
print()
print(y.shape)
print(s.shape)

(3, 4)

(3, 1)
(3, 4)


In [62]:
a = np.zeros((3, 3))
b = np.array([[1, 2, 3]])
print(a)
print()
print(a+b)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]


Let's look at a more complex example.

In [63]:
a = np.random.random((3, 4))
b = np.random.random((3, 1))
c = np.random.random((3, ))

What is the expected broadcasting behavior for these operations? What do the following operations give us? What are the resulting shapes?

In [64]:
result1 = b + b.T

print(b.shape)
print(b.T.shape)
print(result1.shape)
print(result1)

(3, 1)
(1, 3)
(3, 3)
[[0.08547071 0.05210312 0.71378817]
 [0.05210312 0.01873553 0.68042058]
 [0.71378817 0.68042058 1.34210562]]


We see the following code has an error. Why we have this error?

In [65]:
result2 = a + c

print(a.shape)
print(c.shape)
print(result2.shape)
print(result2)

ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

In [66]:
result3 = b + c

print(b.shape)
print(c.shape)
print(result3.shape)
print(result3)

(3, 1)
(3,)
(3, 3)
[[0.54405821 0.88200559 0.46560522]
 [0.51069062 0.848638   0.43223763]
 [1.17237567 1.51032304 1.09392267]]


In [67]:
print(b)
print(c)
print(result3)

[[0.04273536]
 [0.00936777]
 [0.67105281]]
[0.50132286 0.83927023 0.42286986]
[[0.54405821 0.88200559 0.46560522]
 [0.51069062 0.848638   0.43223763]
 [1.17237567 1.51032304 1.09392267]]


### Efficient NumPy Code

When working with numpy arrays, avoid explicit for-loops over indices/axes at all costs. For-loops will dramatically slow down your code (~10-100x).

We can time code using the %%timeit magic. Let's compare using explicit for-loop vs. using numpy operations.

In [68]:
%%timeit
x = np.random.rand(1000, 1000)
for i in range(100, 1000):
    for j in range(x.shape[1]):
        x[i, j] += 5

346 ms ± 8.81 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [69]:
%%timeit
x = np.random.rand(1000, 1000)
x[np.arange(100,1000), :] += 5

12.9 ms ± 2.09 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


### List comprehensions

When programming, frequently we want to transform one type of data into another. As a simple example, consider the following code that computes square numbers:

In [70]:
nums = [0, 1, 2, 3, 4]
squares = []
for x in nums:
    squares.append(x ** 2)
print(squares)

[0, 1, 4, 9, 16]


You can make this code simpler using a list comprehension:

In [71]:
nums = [0, 1, 2, 3, 4]
squares = [x ** 2 for x in nums]
print(squares)

[0, 1, 4, 9, 16]


List comprehensions can also contain conditions:

In [72]:
nums = [0, 1, 2, 3, 4]
even_squares = [x ** 2 for x in nums if x % 2 == 0]
print(even_squares)

[0, 4, 16]


Dictionary comprehensions: These are similar to list comprehensions, but allow you to easily construct dictionaries. For example:

In [73]:
nums = [0, 1, 2, 3, 4]
even_num_to_square = {x: x ** 2 for x in nums if x % 2 == 0}
print(even_num_to_square)

{0: 0, 2: 4, 4: 16}
